### ISSUE TITLE
Various defects in router, AppBar and Drawer

### ISSUE THREAD

**Issue by kiranparajuli589** [KhelkudNepal/KhelkudWeb#25]
### Todos
- [x] The `name of the router` is used to show `title` in `AppBar` but many routers do not have names. #24
- [x] Console error due to uninitialized and unused variable `i` in AppBar (after #22 ) which should be fixed. #24
- [x] Always show the `title` on AppBar (currently invisible in medium or small screens) #24
- [x] Remove `expand on hover` property form dashboard drawer. #24
- [ ] Double items get an `active` class in the dashboard drawer.
